using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading.Tasks;

namespace Eobw.BlueskySharp.Endpoints.Com.Atproto
{
    public class Identity : BlueskyEndpointBase
    {
        // NOTE: This source is auto-generated by Lexicon JSON Conveter beta.

        /// <summary>
        /// Initializes new instance of <see cref="Identity"/> class.
        /// </summary>
        /// <param name="parent">Specify instance of <see cref="BlueskyService"/>.</param>
        internal Identity(BlueskyService parent)
            :base(parent)
        {
            // NOP
        }

        /// <summary>
        /// Updates the handle of the account.
        /// (com.atproto.identity.updateHandle)
        /// </summary>
        /// <param name="Handle">(Handle)</param>
        public void UpdateHandle(string Handle)
        {
            Task.Run(async () => await UpdateHandleAsync(Handle)).Wait();
        }

        /// <summary>
        /// Updates the handle of the account. (Async)
        /// (com.atproto.identity.updateHandle)
        /// </summary>
        /// <param name="Handle">(Handle)</param>
        public async Task UpdateHandleAsync(string Handle)
        {
            var endpointName = "com.atproto.identity.updateHandle";
            var parameterJsonObject = new JsonObject();
            if (Handle != default(string)) parameterJsonObject["handle"] = Handle;

            await this.Parent.InvokeJsonRequestAsync(endpointName, parameterJsonObject);
        }

    }
}

