using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading.Tasks;

namespace Eobw.BlueskySharp.Endpoints.Com.Atproto
{
    public class Repo : BlueskyEndpointBase
    {
        // NOTE: This source is auto-generated by Lexicon JSON Conveter beta.

        /// <summary>
        /// Initializes new instance of <see cref="Repo"/> class.
        /// </summary>
        /// <param name="parent">Specify instance of <see cref="BlueskyService"/>.</param>
        internal Repo(BlueskyService parent)
            :base(parent)
        {
            // NOP
        }

        /// <summary>
        /// Apply a batch transaction of creates, updates, and deletes.
        /// (com.atproto.repo.applyWrites)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Writes">(Writes)</param>
        /// <param name="Validate">(Validate)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public void ApplyWrites(string Repo /* Unsupported: Object[] Writes */, bool Validate = default(bool), string SwapCommit = default(string))
        {
            Task.Run(async () => await ApplyWritesAsync(Repo, Validate, SwapCommit)).Wait();
        }

        /// <summary>
        /// Apply a batch transaction of creates, updates, and deletes. (Async)
        /// (com.atproto.repo.applyWrites)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Writes">(Writes)</param>
        /// <param name="Validate">(Validate)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public async Task ApplyWritesAsync(string Repo /* Unsupported: Object[] Writes */, bool Validate = default(bool), string SwapCommit = default(string))
        {
            var endpointName = "com.atproto.repo.applyWrites";
            var parameterJsonObject = new JsonObject();
            if (Repo != default(string)) parameterJsonObject["repo"] = Repo;
            /* Unsupported */ // if (Writes != default(Object[])) parameterJsonObject["writes"] = Writes;
            if (Validate != default(bool)) parameterJsonObject["validate"] = Validate;
            if (SwapCommit != default(string)) parameterJsonObject["swapCommit"] = SwapCommit;

            await this.Parent.InvokeJsonRequestAsync(endpointName, parameterJsonObject);
        }

        /// <summary>
        /// Create a new record.
        /// (com.atproto.repo.createRecord)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Collection">(Collection)</param>
        /// <param name="Record">(Record)</param>
        /// <param name="Rkey">(Rkey)</param>
        /// <param name="Validate">(Validate)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public CreateRecordResult CreateRecord(string Repo, string Collection /* Unsupported: Object Record */, string Rkey = default(string), bool Validate = default(bool), string SwapCommit = default(string))
        {
            return Task.Run(async () => await CreateRecordAsync(Repo, Collection, Rkey, Validate, SwapCommit)).Result;
        }

        /// <summary>
        /// Create a new record. (Async)
        /// (com.atproto.repo.createRecord)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Collection">(Collection)</param>
        /// <param name="Record">(Record)</param>
        /// <param name="Rkey">(Rkey)</param>
        /// <param name="Validate">(Validate)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public async Task<CreateRecordResult> CreateRecordAsync(string Repo, string Collection /* Unsupported: Object Record */, string Rkey = default(string), bool Validate = default(bool), string SwapCommit = default(string))
        {
            var endpointName = "com.atproto.repo.createRecord";
            var parameterJsonObject = new JsonObject();
            if (Repo != default(string)) parameterJsonObject["repo"] = Repo;
            if (Collection != default(string)) parameterJsonObject["collection"] = Collection;
            /* Unsupported */ // if (Record != default(Object)) parameterJsonObject["record"] = Record;
            if (Rkey != default(string)) parameterJsonObject["rkey"] = Rkey;
            if (Validate != default(bool)) parameterJsonObject["validate"] = Validate;
            if (SwapCommit != default(string)) parameterJsonObject["swapCommit"] = SwapCommit;

            var result = await this.Parent.InvokeJsonRequestAsync(endpointName, parameterJsonObject);
            return CreateRecordResult.FromJsonObject(result);
        }

        /// <summary>
        /// Delete a record, or ensure it doesn't exist.
        /// (com.atproto.repo.deleteRecord)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Collection">(Collection)</param>
        /// <param name="Rkey">(Rkey)</param>
        /// <param name="SwapRecord">(SwapRecord)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public void DeleteRecord(string Repo, string Collection, string Rkey, string SwapRecord = default(string), string SwapCommit = default(string))
        {
            Task.Run(async () => await DeleteRecordAsync(Repo, Collection, Rkey, SwapRecord, SwapCommit)).Wait();
        }

        /// <summary>
        /// Delete a record, or ensure it doesn't exist. (Async)
        /// (com.atproto.repo.deleteRecord)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Collection">(Collection)</param>
        /// <param name="Rkey">(Rkey)</param>
        /// <param name="SwapRecord">(SwapRecord)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public async Task DeleteRecordAsync(string Repo, string Collection, string Rkey, string SwapRecord = default(string), string SwapCommit = default(string))
        {
            var endpointName = "com.atproto.repo.deleteRecord";
            var parameterJsonObject = new JsonObject();
            if (Repo != default(string)) parameterJsonObject["repo"] = Repo;
            if (Collection != default(string)) parameterJsonObject["collection"] = Collection;
            if (Rkey != default(string)) parameterJsonObject["rkey"] = Rkey;
            if (SwapRecord != default(string)) parameterJsonObject["swapRecord"] = SwapRecord;
            if (SwapCommit != default(string)) parameterJsonObject["swapCommit"] = SwapCommit;

            await this.Parent.InvokeJsonRequestAsync(endpointName, parameterJsonObject);
        }

        /// <summary>
        /// Write a record, creating or updating it as needed.
        /// (com.atproto.repo.putRecord)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Collection">(Collection)</param>
        /// <param name="Rkey">(Rkey)</param>
        /// <param name="Record">(Record)</param>
        /// <param name="Validate">(Validate)</param>
        /// <param name="SwapRecord">(SwapRecord)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public PutRecordResult PutRecord(string Repo, string Collection, string Rkey /* Unsupported: Object Record */, bool Validate = default(bool), string SwapRecord = default(string), string SwapCommit = default(string))
        {
            return Task.Run(async () => await PutRecordAsync(Repo, Collection, Rkey, Validate, SwapRecord, SwapCommit)).Result;
        }

        /// <summary>
        /// Write a record, creating or updating it as needed. (Async)
        /// (com.atproto.repo.putRecord)
        /// </summary>
        /// <param name="Repo">(Repo)</param>
        /// <param name="Collection">(Collection)</param>
        /// <param name="Rkey">(Rkey)</param>
        /// <param name="Record">(Record)</param>
        /// <param name="Validate">(Validate)</param>
        /// <param name="SwapRecord">(SwapRecord)</param>
        /// <param name="SwapCommit">(SwapCommit)</param>
        public async Task<PutRecordResult> PutRecordAsync(string Repo, string Collection, string Rkey /* Unsupported: Object Record */, bool Validate = default(bool), string SwapRecord = default(string), string SwapCommit = default(string))
        {
            var endpointName = "com.atproto.repo.putRecord";
            var parameterJsonObject = new JsonObject();
            if (Repo != default(string)) parameterJsonObject["repo"] = Repo;
            if (Collection != default(string)) parameterJsonObject["collection"] = Collection;
            if (Rkey != default(string)) parameterJsonObject["rkey"] = Rkey;
            /* Unsupported */ // if (Record != default(Object)) parameterJsonObject["record"] = Record;
            if (Validate != default(bool)) parameterJsonObject["validate"] = Validate;
            if (SwapRecord != default(string)) parameterJsonObject["swapRecord"] = SwapRecord;
            if (SwapCommit != default(string)) parameterJsonObject["swapCommit"] = SwapCommit;

            var result = await this.Parent.InvokeJsonRequestAsync(endpointName, parameterJsonObject);
            return PutRecordResult.FromJsonObject(result);
        }

        /// <summary>
        /// Upload a new blob to be added to repo in a later request.
        /// (com.atproto.repo.uploadBlob)
        /// </summary>
        public UploadBlobResult UploadBlob()
        {
            return Task.Run(async () => await UploadBlobAsync()).Result;
        }

        /// <summary>
        /// Upload a new blob to be added to repo in a later request. (Async)
        /// (com.atproto.repo.uploadBlob)
        /// </summary>
        public async Task<UploadBlobResult> UploadBlobAsync()
        {
            var endpointName = "com.atproto.repo.uploadBlob";
            var parameterJsonObject = new JsonObject();

            var result = await this.Parent.InvokeJsonRequestAsync(endpointName, parameterJsonObject);
            return UploadBlobResult.FromJsonObject(result);
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class CreateRecordResult
        {
            /// <summary>
            /// 
            /// </summary>
            public string Uri
            {
                get; set;
            }

            /// <summary>
            /// 
            /// </summary>
            public string Cid
            {
                get; set;
            }

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                if (this.Uri != default(string)) result["uri"] = this.Uri;
                if (this.Cid != default(string)) result["cid"] = this.Cid;
                return result;
            }

            public static CreateRecordResult FromJsonObject(JsonObject source)
            {
                var result = new CreateRecordResult();
                if (source.ContainsKey("uri")) result.Uri = (string)source["uri"];
                if (source.ContainsKey("cid")) result.Cid = (string)source["cid"];
                return result;
            }
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class PutRecordResult
        {
            /// <summary>
            /// 
            /// </summary>
            public string Uri
            {
                get; set;
            }

            /// <summary>
            /// 
            /// </summary>
            public string Cid
            {
                get; set;
            }

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                if (this.Uri != default(string)) result["uri"] = this.Uri;
                if (this.Cid != default(string)) result["cid"] = this.Cid;
                return result;
            }

            public static PutRecordResult FromJsonObject(JsonObject source)
            {
                var result = new PutRecordResult();
                if (source.ContainsKey("uri")) result.Uri = (string)source["uri"];
                if (source.ContainsKey("cid")) result.Cid = (string)source["cid"];
                return result;
            }
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class UploadBlobResult
        {
            /// <summary>
            /// 
            /// </summary>
            public Object Blob
            {
                get; set;
            }

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                //if (this.Blob != default(Object)) result["blob"] = this.Blob;
                return result;
            }

            public static UploadBlobResult FromJsonObject(JsonObject source)
            {
                var result = new UploadBlobResult();
                if (source.ContainsKey("blob")) result.Blob = (Object)source["blob"];
                return result;
            }
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class Create
        {
            /// <summary>
            /// 
            /// </summary>
            public string Collection
            {
                get; set;
            }

            /// <summary>
            /// 
            /// </summary>
            public string Rkey
            {
                get; set;
            }

            /* JSON Convertion Unsupported
            /// <summary>
            /// 
            /// </summary>
            public Object Value
            {
                get; set;
            }
            */

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                if (this.Collection != default(string)) result["collection"] = this.Collection;
                if (this.Rkey != default(string)) result["rkey"] = this.Rkey;
                /* Unsupported */ // if (this.Value != default(Object)) result["value"] = this.Value;
                return result;
            }

            public static Create FromJsonObject(JsonObject source)
            {
                var result = new Create();
                if (source.ContainsKey("collection")) result.Collection = (string)source["collection"];
                if (source.ContainsKey("rkey")) result.Rkey = (string)source["rkey"];
                /* Unsupported */ // if (source.ContainsKey("value")) result.Value = (Object)source["value"];
                return result;
            }
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class Update
        {
            /// <summary>
            /// 
            /// </summary>
            public string Collection
            {
                get; set;
            }

            /// <summary>
            /// 
            /// </summary>
            public string Rkey
            {
                get; set;
            }

            /* JSON Convertion Unsupported
            /// <summary>
            /// 
            /// </summary>
            public Object Value
            {
                get; set;
            }
            */

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                if (this.Collection != default(string)) result["collection"] = this.Collection;
                if (this.Rkey != default(string)) result["rkey"] = this.Rkey;
                /* Unsupported */ // if (this.Value != default(Object)) result["value"] = this.Value;
                return result;
            }

            public static Update FromJsonObject(JsonObject source)
            {
                var result = new Update();
                if (source.ContainsKey("collection")) result.Collection = (string)source["collection"];
                if (source.ContainsKey("rkey")) result.Rkey = (string)source["rkey"];
                /* Unsupported */ // if (source.ContainsKey("value")) result.Value = (Object)source["value"];
                return result;
            }
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class Delete
        {
            /// <summary>
            /// 
            /// </summary>
            public string Collection
            {
                get; set;
            }

            /// <summary>
            /// 
            /// </summary>
            public string Rkey
            {
                get; set;
            }

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                if (this.Collection != default(string)) result["collection"] = this.Collection;
                if (this.Rkey != default(string)) result["rkey"] = this.Rkey;
                return result;
            }

            public static Delete FromJsonObject(JsonObject source)
            {
                var result = new Delete();
                if (source.ContainsKey("collection")) result.Collection = (string)source["collection"];
                if (source.ContainsKey("rkey")) result.Rkey = (string)source["rkey"];
                return result;
            }
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class Record
        {
            /// <summary>
            /// 
            /// </summary>
            public string Uri
            {
                get; set;
            }

            /// <summary>
            /// 
            /// </summary>
            public string Cid
            {
                get; set;
            }

            /* JSON Convertion Unsupported
            /// <summary>
            /// 
            /// </summary>
            public Object Value
            {
                get; set;
            }
            */

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                if (this.Uri != default(string)) result["uri"] = this.Uri;
                if (this.Cid != default(string)) result["cid"] = this.Cid;
                /* Unsupported */ // if (this.Value != default(Object)) result["value"] = this.Value;
                return result;
            }

            public static Record FromJsonObject(JsonObject source)
            {
                var result = new Record();
                if (source.ContainsKey("uri")) result.Uri = (string)source["uri"];
                if (source.ContainsKey("cid")) result.Cid = (string)source["cid"];
                /* Unsupported */ // if (source.ContainsKey("value")) result.Value = (Object)source["value"];
                return result;
            }
        }

        /// <summary>
        /// Entity
        /// </summary>
        public class Main
        {
            /// <summary>
            /// 
            /// </summary>
            public string Uri
            {
                get; set;
            }

            /// <summary>
            /// 
            /// </summary>
            public string Cid
            {
                get; set;
            }

            public JsonObject ToJsonObject()
            {
                var result = new JsonObject();
                if (this.Uri != default(string)) result["uri"] = this.Uri;
                if (this.Cid != default(string)) result["cid"] = this.Cid;
                return result;
            }

            public static Main FromJsonObject(JsonObject source)
            {
                var result = new Main();
                if (source.ContainsKey("uri")) result.Uri = (string)source["uri"];
                if (source.ContainsKey("cid")) result.Cid = (string)source["cid"];
                return result;
            }
        }

    }
}

